# Generated by Django 4.2.9 on 2024-05-29 03:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0003_alter_mascota_foto_mas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=50, verbose_name='Nombre de categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Publicar_Mas',
            fields=[
                ('id_pubm', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pubm', models.DateField(auto_now_add=True)),
                ('descripcion_pubm', ckeditor.fields.RichTextField(verbose_name='Descripción de la mascota')),
                ('foto_pubm', models.ImageField(upload_to='PublicMas/', verbose_name='Foto')),
                ('mascota_pubm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mascota.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Mascotas Publicadas',
                'verbose_name_plural': 'Mascotas Publicadas',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.AutoField(primary_key=True, serialize=False)),
                ('foto_blog', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen')),
                ('titulo_blog', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido_blog', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('creado_blog', models.DateField(auto_now_add=True)),
                ('categoria_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicacion.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
