# Generated by Django 4.2.9 on 2024-05-29 03:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0003_alter_mascota_foto_mas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dpi_persona', models.IntegerField(primary_key=True, serialize=False, verbose_name='DPI')),
                ('nombre_p', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_p', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('edad_p', models.IntegerField(verbose_name='Edad')),
                ('direccion_p', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono_p', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('redes_p', models.CharField(max_length=50, verbose_name='Redes')),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_adop', models.DateField(auto_now_add=True)),
                ('preguntas_adop', ckeditor.fields.RichTextField(default='preguntas para adoptar', verbose_name='Formulario')),
                ('mascota_adop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mascota.mascota', verbose_name='Mascota')),
                ('persona_adop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adopcion.persona', verbose_name='Adoptante')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
            },
        ),
    ]
