# Generated by Django 4.2.9 on 2024-08-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcion',
            options={'verbose_name': 'Adopción', 'verbose_name_plural': 'Mascotas adoptadas'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Crear Adopción'},
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='persona_adop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='Adopcion.persona', verbose_name='Adoptante'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='preguntas_adop',
            field=models.TextField(default='preguntas para adoptar', verbose_name='Formulario'),
        ),
    ]
