# Generated by Django 4.2.9 on 2024-05-14 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=50, verbose_name='Lugar')),
                ('zona_lugar', models.IntegerField(verbose_name='Zona')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_med', models.CharField(max_length=50, verbose_name='Nombre Medicamento')),
                ('precio_med', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precio')),
                ('descripcion_med', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_raza', models.CharField(max_length=50, verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mas', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de rescate')),
                ('nombre_mas', models.CharField(max_length=50, verbose_name='Nombre')),
                ('especie_mas', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], default='P', max_length=20, verbose_name='Especie')),
                ('sexo_mas', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=20, verbose_name='Sexo')),
                ('edad_mas', models.IntegerField(verbose_name='Edad aproximada')),
                ('color_mas', models.CharField(max_length=30, verbose_name='Color')),
                ('observacion_mas', models.CharField(blank=True, max_length=100, verbose_name='Observaciones')),
                ('esteril_mas', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=20, verbose_name='¿Esterilizado?')),
                ('foto_mas', models.ImageField(upload_to='', verbose_name='Fotografía')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateField(auto_now_add=True)),
                ('lugar_mas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mascota.lugar', verbose_name='Lugar de rescate')),
                ('raza_mas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mascota.raza', verbose_name='Raza')),
            ],
        ),
        migrations.CreateModel(
            name='AdministracionMedicamento',
            fields=[
                ('id_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_administracion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de administración')),
                ('dosis_administrada', models.CharField(blank=True, max_length=50, verbose_name='Dosis administrada')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mascota', to='Mascota.mascota')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medicamento', to='Mascota.medicamento')),
            ],
        ),
    ]
