# Generated by Django 4.2.9 on 2024-05-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_mas',
            field=models.ImageField(upload_to='mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='lugar_mas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascota.lugar', verbose_name='Lugar de rescate'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_mas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascota.raza', verbose_name='Raza'),
        ),
    ]
