# Generated by Django 4.2.9 on 2024-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_alter_mascota_foto_mas_alter_mascota_lugar_mas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_mas',
            field=models.ImageField(upload_to='mascota/', verbose_name='Foto'),
        ),
    ]
