# Generated by Django 4.2.9 on 2024-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0003_alter_mascota_foto_mas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_mas',
            field=models.ImageField(upload_to='mascota', verbose_name='Foto'),
        ),
    ]
